export const catList = [
  { category: "Chair" },
  { category: "Sofa" },
  { category: "Table" },
  { category: "Couch" },
  { category: "Bed" },
  { category: "Wardrobe" },
  { category: "TV Rack" },
  { category: "Wall Trangle" },
  { category: "Beehive" },
  { category: "Bed Side Table" },
  { category: "Lamp" },
  { category: "Hangers" },
  { category: "Stands" },
];
