export const imageData = [
  {
    id: 0,
    category: "Chair",
    img: "/img/chair.jpeg",
    head: "Chair",
    price: "Rs. 10,000",
  },
  {
    id: 2,
    category: "Hangers",
    img: "/img/armchair-3.jpg",
    head: "Arm Chair",
    price: "Rs. 12,000",
  },
  {
    id: 3,
    category: "Stands",
    img: "/img/bed.jpg",
    head: "Bed",
    price: "Rs. 20,000",
  },

  {
    id: 4,
    category: "Lamp",
    img: "/img/dining-table.jpg",
    head: "Dining Table",
    price: "Rs. 70,000",
  },
  {
    id: 5,
    category: "Bed Side Table",
    img: "/img/sofa.jpg",
    head: "Corner Sofa",
    price: "Rs. 23,000",
  },
  {
    id: 6,
    category: "Beehive",
    img: "/img/chair.jpeg",
    head: "Chair",
    price: "Rs. 2000",
  },
  {
    id: 7,
    category: "Wall Trangle",
    img: "/img/sofa.jpg",
    head: "Sofa",
    price: "Rs. 60,000",
  },
  {
    id: 8,
    category: "TV Rack",
    img: "/img/sofa-2.jpg",
    head: "Sofa Set",
    price: "Rs. 72,000",
  },
  {
    id: 9,
    category: "Couch",
    img: "/img/sofa-3.jpg",
    head: "Sofa Set",
    price: "Rs. 52,000",
  },
  {
    id: 10,
    category: "Wardrobe",
    img: "/img/armchair-4.jpg",
    head: "Arm Chair",
    price: "Rs. 20,000",
  },
  {
    id: 11,
    category: "Table",
    img: "/img/armchair-3.jpg",
    head: "Arm Chair",
    price: "Rs. 25,000",
  },
  {
    id: 12,
    category: "Arm Chair",
    img: "/img/armchair-4.jpg",
    head: "Arm Chair",
    price: "Rs. 32,000",
  },
];
